// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmTBTAZoAklfzgd-xGm2QDBGp00zQB6k4',
    appId: '1:544152754809:web:49b3a3b9c5fc18ae3f12a8',
    messagingSenderId: '544152754809',
    projectId: 'ogrenme-asistani',
    authDomain: 'ogrenme-asistani.firebaseapp.com',
    storageBucket: 'ogrenme-asistani.firebasestorage.app',
    measurementId: 'G-2Z5R89C76M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtabony3iJNR5RFt1WMVkQHfBqiOUf-lk',
    appId: '1:544152754809:android:f0c84d52b63c3f8d3f12a8',
    messagingSenderId: '544152754809',
    projectId: 'ogrenme-asistani',
    storageBucket: 'ogrenme-asistani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBePN3BUNYr0R-53TOa2Pn0-DbGzJw7I',
    appId: '1:544152754809:ios:e186442084ff38d93f12a8',
    messagingSenderId: '544152754809',
    projectId: 'ogrenme-asistani',
    storageBucket: 'ogrenme-asistani.firebasestorage.app',
    iosBundleId: 'com.example.ogrenmeAsistani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBePN3BUNYr0R-53TOa2Pn0-DbGzJw7I',
    appId: '1:544152754809:ios:e186442084ff38d93f12a8',
    messagingSenderId: '544152754809',
    projectId: 'ogrenme-asistani',
    storageBucket: 'ogrenme-asistani.firebasestorage.app',
    iosBundleId: 'com.example.ogrenmeAsistani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmTBTAZoAklfzgd-xGm2QDBGp00zQB6k4',
    appId: '1:544152754809:web:233090908f6af39b3f12a8',
    messagingSenderId: '544152754809',
    projectId: 'ogrenme-asistani',
    authDomain: 'ogrenme-asistani.firebaseapp.com',
    storageBucket: 'ogrenme-asistani.firebasestorage.app',
    measurementId: 'G-983FKE4X8E',
  );
}
